version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "4173"
    environment:
      - VITE_API_URL=http://backend:8000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - PORT=8000
      - JWT_SECRET=mysecret
      - DB_HOST=fieldex.c3ssu4aw8v1d.ap-southeast-2.rds.amazonaws.com
      - DB_USER=admin
      - DB_NAME=FieldEx
      - DB_PASSWORD=12345678
      - DB_PORT=3306

volumes:
  pgdata:
